### ISSUE TITLE
Animation for slides/fragments transition

### ISSUE THREAD

**Issue by garyng** [marp-team/marp-core#110]
Is it possible to have animation for slide transitions and fragments? Fading in/out would be nice!

**Comment by yhatt** [comment]
Marpit and Marp core are designed to render *static* HTML. Implementation of gorgeous animations and transitions is responsibility of tools using that, and not Marp Core.

For example, my practical example in [marp-vue-slide](https://github.com/yhatt/marp-vue-slide) can use transition. Of course fade effect can use by changing [the `effect` option of swiper](https://github.com/yhatt/marp-vue-slide/blob/master/src/App.vue#L25) into `fade`.
https://marp-vue-slide.netlify.com/

**Comment by garyng** [comment]
Thanks!

**Comment by yhatt** [comment]
-> marp-team/marp-cli#382
