### ISSUE TITLE
Code blocks disappear when using markdown-it-plantuml

### ISSUE THREAD

**Issue by Inujel** [marp-team/marp-core#112]
I'm trying to use markdown-it-plantuml.

I'm using marp/cli with this `marp.config.js` file
```js
const { Marp } = require('@marp-team/marp-core')

module.exports = {
    engine: opts => new Marp(opts).use(require('markdown-it-plantuml'))
}
```

Now I have plantuml working, but the content of my code blocks has disappeared
![image](https://user-images.githubusercontent.com/1295051/67013418-609afd00-f0f3-11e9-8333-df2156b868e6.png)

Am I doing something wrong?

**Comment by yhatt** [comment]
I think it's probably the same problem as marp-team/marp-cli#168. When you are using the customized engine through JavaScript, Marp CLI cannot trigger Marp Core's `Marp.ready()` browser script for scaling code block.

Could you try a workaround explained in https://github.com/marp-team/marp-cli/issues/168#issuecomment-538296723? Please add this line to anywhere of Markdown.

```html
<script defer src="https://cdn.jsdelivr.net/npm/@marp-team/marp-core/lib/browser.js"></script>
```

To resolve, it may be the best to inject this tag by Marp Core automatically.

**Comment by Inujel** [comment]
Yep, this is it! Thank you very much.
