### ISSUE TITLE
How should I insert multiple pictures

### ISSUE THREAD

**Issue by AngelinaBao** [marp-team/marp-core#122]
I would like to put multiple, like 6 or 8 pictures in one page, so how should I do in Marp? I tried table, but it looks a little ugly. May I know if any other good method for it?

**Comment by yhatt** [comment]
The easiest way is using multiple `![bg](xxx.jpg)`. See ["multiple backgrounds" at the document of Marpit framework](https://marpit.marp.app/image-syntax?id=multiple-backgrounds).
