### ISSUE TITLE
[Question] how to do autofit so content won't be cropped off?

### ISSUE THREAD

**Issue by gpenghe** [marp-team/marp-core#128]
Firstly thanks for developing this great tool. I just started using it and it's fantastic. The real time previewing in VS Code is like nothing I've seen before :)

In my first test, one slide is not able to hold all the content.  I am wondering if Marp can scale the result to fit all content into one page. (I don't mind the text font will be smaller.)

I've tried to use the following options.

    theme: enable-all-auto-scaling
    auto-scaling: true   

I can see the code block is scaled. But the text lines are still overflown.

**Comment by yhatt** [comment]
I appreciate you using our ecosystem. Unfortunately, we have not `auto-scaling` directive for the whole of page contents.

But you could try to tweak style manually for the best font size.

```markdown
<style scoped>section { font-size: 20px; }</style>
```

[`<style scoped>`](https://marpit.marp.app/theme-css?id=scoped-style) can change font size in the whole of only current page so would be help to fix cropped slide.

**Comment by gpenghe** [comment]
Wow, it works like a charm. Thank you very much.

Now that the content fits in a single slide. Then it comes to the question of whether there's a way to put content to two columns. But maybe I'd better submit a new question for that.

BTW, do you have plan to add feature for `auto-scaling` for the whole page? I haven't taken a look at `Marp` code yet, but would like to see if I can contribute in some ways.

**Comment by yhatt** [comment]
We have no plan of auto-scaling for the slide because HTML and web platform does not have better layout system usable for scaling.

If you are using Mac, [Deckset](https://www.deckset.com/) would help you to scale the content of slide automatically (Mac has a rich layout system like [Core Text](https://en.wikipedia.org/wiki/Core_Text) to suit to auto layout).
