### ISSUE TITLE
Multi-column in a single slide?

### ISSUE THREAD

**Issue by gpenghe** [marp-team/marp-core#132]
Is it possible to have two columns in the same slide?

**Comment by yhatt** [comment]
You can use CSS Multi-column Layout Module such as [`columns` property](https://developer.mozilla.org/en-US/docs/Web/CSS/columns) by tweaking style.

```markdown
<style>
p { columns: 2; }
</style>
```

We have an example to use [multi-column layout in Marpit framework](https://marpit.marp.app/usage?id=extend-marpit-by-plugins).

The advanced usage by creating multi HTML containers has already discussed in https://github.com/marp-team/marpit/issues/137.  In general, Markdown syntax does just not suitable for complex layout so you have to use HTML.

> NOTE: Please keep in mind that GitHub issue tracker is for development and not best place for question. See also contribution guide for projects of our team: https://github.com/marp-team/marp/blob/master/.github/CONTRIBUTING.md#question

**Comment by ptlddn** [comment]
This seems work well with marp and markdown in column. with "--html"
"
A note on this method, to use it with markdown you need to use code like this <section class="hbox">	<div class="container"> <div class="flex-col" data-markdown> * Column 1 Content </div> <div class="flex-col" data-markdown> * Column 2 Content </div> </div> </section> 
"
–From Rod Burns

**Comment by ptlddn** [comment]
This seems work well with  " marp-cli --html"
```
A note on this method, to use it with markdown you need to use code like this <section class="hbox">	<div class="container"> <div class="flex-col" data-markdown> * Column 1 Content </div> <div class="flex-col" data-markdown> * Column 2 Content </div> </div> </section> 
--from  Rod Burns
```
