### ISSUE TITLE
Presenter view

### ISSUE THREAD

**Issue by asm0dey** [marp-team/marp-core#140]
Hello, folks!

Thank you for your amazing work. Marp Next is way more powerful than previous Marp!

It would be super-useful to implement speaker view like reveal.js does [here](https://github.com/hakimel/reveal.js/#speaker-notes)

**Comment by yhatt** [comment]
Presenter view is out of Marp Core's scope. How to show created slide by Marp Core should decide within integrated tool.

Please refer to the same issue and pull request in Marp CLI: https://github.com/marp-team/marp-cli/issues/142, https://github.com/marp-team/marp-cli/pull/157
