### ISSUE TITLE
Feature Request: User themes index

### ISSUE THREAD

**Issue by paulodiovani** [marp-team/marp-core#148]
# Feature description

Create a searchable index for user created themes for marp.

## Ideas

- Can be a simple wiki page, or in the docs.
- Another option would be a repository with a single markdown page with  that the users can add to with pull requests.
- An even easier one is to just define a repository name pattern (e.g. `marp-theme-[name]` and ask theme designers to use it in the theme documentation. So marp themes can be searched in github itself.

**Comment by yhatt** [comment]
Explaining how to publish theme in the entrance repisotry [marp-team/marp](https://github.com/marp-team/marp) would be good.

How about using GitHub topics like https://github.com/topics/marp? I've confirmed a user using [`marp-themes` topic](https://github.com/topics/marp-themes).

**Comment by yhatt** [comment]
For now, Marp team has no time to maintain community index. As I mentioned in #178, we want to leave to our community.

> If you think there is a worth to collect repositories about Marp anyway, try to create your own "awesome-marp" repository referring to [many awesome lists](https://github.com/sindresorhus/awesome)!

_Originally posted by @yhatt in https://github.com/marp-team/marp-core/pull/178#issuecomment-660563166_
