### ISSUE TITLE
Creating documents that are not slides

### ISSUE THREAD

**Issue by eduardo4jesus** [marp-team/marp-core#149]
I can't find how to create regular documents that are not slides with marp. Is there a way to do that?
PS.: I also couldn't find where to post this question, so I am adding it as an issue.

**Comment by yhatt** [comment]
No. Marp is only for creating slide, and the creation of document is out of our scope. Please use the other tool.

There are a lot of tools for creating document from Markdown. (You can find in [awesome-markdown](https://github.com/BubuAnabelas/awesome-markdown#readme))
