### ISSUE TITLE
Import/Include content from other files. Slide grouping and organization.

### ISSUE THREAD

**Issue by eduardo4jesus** [marp-team/marp-core#163]
Hello Marp-Team

Is there a way to include the content of other markdown files into the current one?

I use Marp via the VS Code extension, and my presentations can get quite big and hard to manage slides, their order, maybe group them, etc.

I imagine that by being able to import the content of another presentation into the current one would help me with this.

Is there such a think in marp? Or, are you planning on adding a similar feature in the future?

**Comment by yhatt** [comment]
Duplicated with marp-team/marpit#227. The simple solution already working is using [Marp CLI](https://github.com/marp-team/marp-cli) together with the markdown-it-include plugin: https://www.npmjs.com/package/markdown-it-include.

> Both of Marpit and [Marp Core](https://github.com/marp-team/marp-core) are designed to work in anywhere, not only the local file system but also web app ([Marp Web](https://web.marp.app/)). So _we cannot add the feature depending on local file system as our framework / core_.
