### ISSUE TITLE
Add line based code highlighting

### ISSUE THREAD

**Issue by spinscale** [marp-team/marp-core#168]
Thanks a ton for creating marp, been using it since some time and really like it!

One feature I am missing (or maybe I haven't found it) is the partial highlighting of codeblocks.

Deckset allows for incremental highlighting via its `[.code-highlight: ...]` snippet, I think something similar would be great for marp as well.

**Comment by yhatt** [comment]
Duplicate of marp-team/marp-vscode#146. You already can use line-based code highlight through [markdown-it-highlight-lines](https://github.com/egoist/markdown-it-highlight-lines) plugin.
