### ISSUE TITLE
How to move title up or down?

### ISSUE THREAD

**Issue by humanbeingZ** [marp-team/marp-core#177]
Sorry to bother. 
Is it possible to move the title up or down according to some user defined value?
In the following test page, I'd like to move the title up a little bit. Can it be done?
Thanks!
![image](https://user-images.githubusercontent.com/25080075/87851025-73af5780-c927-11ea-9bb5-4c7adc28bc32.png)

**Comment by yhatt** [comment]
Refer to #78.

For example, the following moves title up in default theme.

```markdown
<style scoped>section { justify-content: start; }</style>

# This is a title
```

Use [`justify-content: end;`](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content) if you want to move title down.

**Comment by humanbeingZ** [comment]
Thanks for the reply! 
Do you mean that there are only a few options for the title position? What if I want to move the title between center and start?

**Comment by yhatt** [comment]
I just gave the one of the simplest way, but of course you can take the other way to make fine positioning:

- Set absolute position of `h1` by using `position: absolute` + `top: XX%`
- Shift the position of `h1` by using `position: relative` + `top: -XXpx`.
- Make the space to `h1`'s bottom through `margin-bottom`
- Use [negative margin](https://css-tricks.com/negative-margins/) to make `h1`'s offset via`margin-top: -XXpx`.

However, it's basic of CSS and *essentially not an issue of Marp*. Probably you are in wrong place to ask. [Read our Marp team's support guideline first.](https://github.com/marp-team/.github/blob/master/SUPPORT.md#question)

**Comment by humanbeingZ** [comment]
Thanks for your detailed reply! 
Sorry for the inconvenience. I'll find some time to learn about CSS.
