### ISSUE TITLE
Option to output an inline helper script without injecting it in HTML

### ISSUE THREAD

**Issue by rdrgn** [marp-team/marp-core#179]
Currently, an inline helper script is injected into only after the last slide. (cf. https://github.com/marp-team/marp-core#script-boolean--object) Therefore, if I use only one of the rendered slides (like `html[slideIndexToDisplay]`), it may not have the script and may not be displayed correctly.

So, I need an option to inject the script into all slides.

However, I thought it would be more flexible to output the script without injecting it in HTML.

```js
const { html, css, js } = marp.render('# Hello, marp-core!')
```

**Comment by yhatt** [comment]
The helper script for Marp Core is immutable. So you already can use the helper function by using `@marp-team/marp-core/browser`.

```javascript
// Require to use bundler (e.g. webpack)
import { Marp } from '@marp-team/marp-core'
import helperScript from '@marp-team/marp-core/browser'

// Just work by calling it once on the browser context
helperScript()

// Need to disable script injection into the last page
const marp = new Marp({ script: false })
const { html, css } = marp.render('# Hello, marp-core!')
```

**Comment by rdrgn** [comment]
I am working on isolating rendered slides using `iframe` because, in Safari, outer styles often break the layouts of elements in `svg`. It would be nice to be able to run `helperScript()` in an `iframe`, is there a way to do that?

Sorry for my ignorance of JavaScript and HTML.

**Comment by yhatt** [comment]
I don't know how to use iframe of yours, but typically you should contain the script together with a generated page as the content of iframe.

If you can't use JS bundler by some reason, just adding HTML tag `<script src="https://cdn.jsdelivr.net/npm/@marp-team/marp-core@1.2.2/lib/browser.js" defer></script>` would work. It's same as the injected helper by `new Marp({ script: { source: 'cdn' } })`.

**Comment by rdrgn** [comment]
> If you can't use JS bundler by some reason, just adding HTML tag `<script src="https://cdn.jsdelivr.net/npm/@marp-team/marp-core@1.2.2/lib/browser.js" defer></script>` would work. It's same as the injected helper by `new Marp({ script: { source: 'cdn' } })`.

I was aware of it. I wanted to apply polyfills without external resources but now I understand I should take this problem into my own hands.

> Using CDN is safer than embedding the inline script, because it may be blocked by Content-Security-Policy.

Yes, indeed!

Thank you for replying to my issue!
