### ISSUE TITLE
A dynamically generated image does not have the correct size

### ISSUE THREAD

**Issue by timoguic** [marp-team/marp-core#193]
Hello,

And thanks for creating Marp. It has become my main tool to work on slides.
There is one thing that I cannot get to work properly - I want to use PlantUML in my slides.
I used [mardown-it-plantuml](https://github.com/gmunguia/markdown-it-plantuml). I can see the image, but it is distorted:

![distorted UML diagram](https://user-images.githubusercontent.com/637649/93492404-9de9ab00-f8bf-11ea-9e28-e2ed90e24844.png)

I am using Marp CLI with a custom `marp.config.js` (like mentioned in #112). I found #131 which seems to relate to my problem. I tried making my own `engine.js`, with the same result. I also know that Marp does not officially support the PlantUML plugin, but is there an easy way to fix it on my side? I tried to use SVG and PNG, and looked at CSS options for SVG objects, to no avail.

Thanks a lot.

**Comment by yhatt** [comment]
Probably a UML image is rendering as the block-style element. Some themes by Marp Core will stretch direct children elements of the container `<section>` flex element into the whole of width, through [`align-items: stretch`](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items).

You can patch the style in Markdown to prevent expanding: [`align-self: flex-start`](https://developer.mozilla.org/en-US/docs/Web/CSS/align-self).

```markdown
<style>
section > img {
  align-self: flex-start;
}
</style>

# UML example:

@startuml
Bob -> Alice : hello
@enduml
```

> [In CommonMark, images should place within `<p>` tag](https://spec.commonmark.org/0.29/#images) but markdown-it-plantuml is not following this. If it had rendered UML images on-spec, you would have required no patches.

**Comment by timoguic** [comment]
Thank you very much for the answer, the fix, and the additional explanation!
