### ISSUE TITLE
No parsing of transparent background for PNG images

### ISSUE THREAD

**Issue by wleoncio** [marp-team/marp-core#196]
# Summary

PNG images with transparent backgrounds are rendered with white backgrounds

# MRE

```md
---
marp: true
---

<!--
	backgroundColor: blue
	color : white
-->

# Testing image

![w:500](http://www.pngall.com/wp-content/uploads/2016/04/Plum-Free-PNG-Image.png)
```

# Expected result
Something like this (sans sloppy paintjob)
![image](https://user-images.githubusercontent.com/8234768/95455180-c409e480-096d-11eb-887c-f8076ceffc6b.png)

# Obtained result
![image](https://user-images.githubusercontent.com/8234768/95454967-71302d00-096d-11eb-946b-c2d86f9a2924.png)

**Comment by wleoncio** [comment]
That's all it took, thank you very much!

BTW, I actually find it convenient that the default theme is tied to GitHub's Markdown style (however featureless it is), but as someone with very rudimentary CSS skills, I wish this specific tip was part of the Marp documentation (I couldn't find it anywhere).

Cheers \o

**Comment by yhatt** [comment]
Thanks! I'll give your feedback to [working unified documentation](https://marp.app/blog/re-creation-of-marp-website).
