### ISSUE TITLE
Vertical fit

### ISSUE THREAD

**Issue by harsh183** [marp-team/marp-core#197]
I use marp for a lot of programming related presentations but sometimes what happens is that slides get too long vertically. The elements adjust well based on horizontal line size but I can't figure out a way to do this from reading all the docs and example decks. 

Sometimes I end up removing titles and other text to push to another slide but I think I'd prefer it if it scales the slide vertically over having a cut out at the top and bottom.

**Comment by harsh183** [comment]
What about just having code blocks itself scale? Like not the slide itself but having it scale down. How do you set up settings for code blocks, the docs aren't the most clear?

```
# <!-- fit --> Heading
```

Stuff like this is fine, what about code blocks?

**Comment by yhatt** [comment]
Housekeeping 🧹
