### ISSUE TITLE
Make built-in theme customization easy through CSS variables

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-core#209]
Continue from marp-team/marp#48. Marp built-in themes are made by Sass and some themes are using mixin-based color scheme definition.
https://github.com/marp-team/marp-core/tree/master/themes

However it makes difficult to change theme color through tweaking style by `<style>` because some color schemes are defined as Sass variables. Some users are confusing to the fact that still require Sass compiler just for customize colors (marp-team/marp#73).

So must be better to move into using CSS variables. The legacy browser that has not supported CSS variables is already no longer required to consider.

> :warning: This migration may make broken the look of exist Marp slides so this change must be the major update.

### ToDo

- [x] Default theme (v3)
- [x] Gaia theme (v2.0.0)
- [x] Uncover theme (v2.0.0)

**Comment by yhatt** [comment]
Marp Core v2.0.0 has supported setting color scheme through CSS variables, in Gaia theme and Uncover theme. See https://github.com/marp-team/marp-core/pull/221 for detail.

:warning: Default theme is not yet ready to customize color scheme through CSS variables. It is depending on [`github-markdown-css`](https://github.com/sindresorhus/github-markdown-css) and not provided variables-based color definition as like as GitHub's dark mode. Current `invert` class has many unique definitions against the current GitHub dark mode so it seems wise to wait for the support of variables used by GitHub.

**Comment by vedranmiletic** [comment]
What is the new way to change presentation font on the Default theme? The code I found on some issue a while ago

```html
<style>
section {
 font-family: 'Roboto', 'Segoe UI', 'Liberation Sans', 'Helvetica', 'Arial', sans-serif;
}
</style>
```

no longer has any effect in either HTML or PDF.

**Comment by yhatt** [comment]
@vedranmiletic Please don't take over potentially not-related issue for ask something.

There is no change for the default theme by this issue and related pull requests. Instead, you are welcome to ask in our discussion forum. https://github.com/marp-team/marp/discussions
