### ISSUE TITLE
Support for tasklist/radio button/checkbox

### ISSUE THREAD

**Issue by TomL-dev** [marp-team/marp-core#238]
Hi,

I'm looking for support for checkboxes

- [ ] just
- [x] like
- [ ] this

like: https://github.blog/2014-04-28-task-lists-in-all-markdown-documents/

currently it's rendered like (in html): 

![image](https://user-images.githubusercontent.com/26207844/121181862-c0af5b80-c862-11eb-9b5a-4c3a47cf23e3.png)

is there a way to do this?

**Comment by yhatt** [comment]
You can use [markdown-it-task-lists](https://github.com/revin/markdown-it-task-lists) plugin.

```javascript
const { Marp } = require('@marp-team/marp-core')
const tasklists = require('markdown-it-task-lists')

const marp = new Marp().use(tasklists)
marp.render('- [ ] xxx')
```

https://github.com/marp-team/marp-cli#functional-engine

**Comment by yhatt** [comment]
Check out marp-team/marp#41.

```js
// engine.js
const { Marp } = require('@marp-team/marp-core')
const tasklists = require('markdown-it-task-lists')

module.exports = (opts) => new Marp(opts).use(tasklists)
```

```bash
npm install @marp-team/marp-core @marp-team/marp-cli markdown-it-task-list --save-dev
npx marp --engine ./engine.js slide-deck.md
```

**Comment by indranilrc** [comment]
Is there a way to use plugins when using Marp on VSCode? Thanks!

**Comment by yhatt** [comment]
Marp team does not intend to support custom plugins in VS Code, due to the inconsistent result between the preview and the output, and [a potential security issue](https://github.com/marp-team/marp/discussions/207#discussioncomment-2443316). We do not want to put our users at risk.
