### ISSUE TITLE
Type Error after trying to bundle marp-core with rolllup 

### ISSUE THREAD

**Issue by bjesuiter** [marp-team/marp-core#259]
Hi Marp Team, 

I currently try to implement your marp-core as a plugin for [Obsidian](https://obsidian.md/). 
My Repo is here: https://github.com/bjesuiter/obsidian-marp-presentations (Only for reference) 

**The problem**:
When my Plugin file loads, it throws this error
> TypeError: Cannot read property 'MathtoolsMethods' of undefined

Here is a screenshot of the error
<img width="1904" alt="Bildschirmfoto 2021-10-04 um 18 19 07" src="https://user-images.githubusercontent.com/2365676/135887579-84b8a9c9-5843-46ad-8c2f-daa08faa64f8.png">

**My Assumption:**
The error comes from something missing in my rollup pipeline, so that bundling breaks.
Reason: it works before the latest commit: 
[My Commits](https://github.com/bjesuiter/obsidian-marp-presentations/commits/main)
[My Latest Commit](https://github.com/bjesuiter/obsidian-marp-presentations/commit/85a2dc5eb35829a3dcd21c428e8bdcd6f0a9ac5d)

Since I don't use my own markdown currently, it can't be an error with that. 

Thank you for reading my problem and hopefully you can help me solve it, since I'm relatively lost here :/

**Comment by yhatt** [comment]
[`MathtoolsMethods` seems to come from MathJax.](https://github.com/search?q=MathtoolsMethods&type=code) Did not rollup emit circular dependency warnings when building? rollup may not be able to resolve CommonJS export correctly if there is circular dependency in a module. As the result, sometimes it might throw undefined property error just like that.

Marp team is bundling Marp Core through webpack in sub-projects like marp-vscode, and it works well. We have to look into bundling issue on rollup.

**Comment by bjesuiter** [comment]
Ahh, interesting! 
When I build in verbose mode, I see a circular dependency warning, as you expected! 

```
(!) Circular dependenciestiming npm:load Completed in 31ms
node_modules/mathjax-full/js/input/tex/TexParser.js -> node_modules/mathjax-full/js/input/tex/ParseUtil.js -> node_modules/mathjax-full/js/input/tex/TexParser.js
node_modules/mathjax-full/js/input/tex/TexParser.js -> node_modules/mathjax-full/js/input/tex/ParseUtil.js -> /Users/bjesuiter/Develop/obsidian/obsidian-marp-presentations/node_modules/mathjax-full/js/input/tex/TexParser.js?commonjs-proxy -> node_modules/mathjax-full/js/input/tex/TexParser.js
node_modules/mathjax-full/js/input/tex/mathtools/MathtoolsMethods.js -> node_modules/mathjax-full/js/input/tex/mathtools/MathtoolsUtil.js -> node_modules/mathjax-full/js/input/tex/mathtools/MathtoolsMethods.js
...and 5 more
```

**Comment by bjesuiter** [comment]
Another Update: 

It seems that I can add the mathjax module as dynamicRequireTarget, which fixes the circular dependency problem 
(e.g. I can compile without a warning): 

```
dynamicRequireTargets: [
				// Inside mathjax is the following circular dependency:
				// node_modules/mathjax-full/js/input/tex/TexParser.js
				// -> node_modules/mathjax-full/js/input/tex/ParseUtil.js
				// -> node_modules/mathjax-full/js/input/tex/TexParser.js
				// This simulates a dynamic 'require' environment for the whole mathjax library to resolve the problem
				`node_modules/mathjax-full/**/*.js`,
			],
```

The problem is now, that the imports do not seem to be working. 

<img width="774" alt="Bildschirmfoto 2021-10-04 um 22 25 41" src="https://user-images.githubusercontent.com/2365676/135919771-63b22e89-4a72-42a5-8898-2e397e446f69.png">

I will play around with these values a bit, maybe I can make it work. 

BTW: Thank you so much for looking into it that fast! <3

**Comment by yhatt** [comment]
Now [obsidian-sample-plugin](https://github.com/obsidianmd/obsidian-sample-plugin) is using esbuild instead of rollup, and it can bundle Marp Core straightly. Marp is available in Obsidian :point_down: 

![](https://user-images.githubusercontent.com/3993388/167843946-b24eff1f-f478-40d2-bed1-5aeca0e95ea2.png)

It is good for developers to know the thing that rollup cannot bundle Marp Core due to MathJax's circular dependency.

We close this because should keep cleaning up the issue tracker to focus Marp improvements.

**Comment by bjesuiter** [comment]
Thank you very much for looking into it, i unfortunately haven't came around to implement the new things yet. 
But it's nice to now that they're available! I think, my Issue will be resolved with this now. 
Thanks again!
