### ISSUE TITLE
Embedded svg in presentation

### ISSUE THREAD

**Issue by pprw** [marp-team/marp-core#278]
I have a presentation with several svg graphs (produced by draw.io).

I work fine from my computer but svg are not displayed when I send my html presentation to other.

How can I embedded svg image to create a portable .html file?

**Comment by yhatt** [comment]
Marp team always recommends to use SVG images from remote URL `https://....`, but marp-team/marp#132 may be helpful to your use case.

**Comment by pprw** [comment]
Thks! Monolith did the job.
