### ISSUE TITLE
Mathjax formulas looking "bold" when exported to pdf on some pdf viewers

### ISSUE THREAD

**Issue by Prki42** [marp-team/marp-core#287]
### Version of Marp Tool

Marp CLI v1.7.0

### Operating System

Windows

### Environment

- OS version: Windows 10 (running in wsl2)
- WSL Ubuntu version:  Ubuntu 20.04.3 LTS
- Node.js version: v17.3.0
- Marp CLI version: v1.7.0
- Marp core version: v2.3.2

### How to reproduce

1. Use `mathjax` for math formulas
2. Export pdf using `marp` cli
3. Open pdf in web browser (tried in Firefox, Chrome and Microsoft Edge)

### Expected behavior

This is how it looks when using html preview
![firefox_eRrUJKUK0L](https://user-images.githubusercontent.com/48697336/155861452-fbd9599e-3054-49b5-812f-9639b6626ccd.png)

### Actual behavior

Looks a bit bolder than when using html preview
![firefox_vyYMJND3ZP](https://user-images.githubusercontent.com/48697336/155861420-b6a16889-5bc7-4e63-8bb2-04b59629c060.png)

When zoomed out
![firefox_7D3HSvDeSk](https://user-images.githubusercontent.com/48697336/155861422-57c952b2-866f-4c72-8515-8296c08faba1.png)

### Additional information

This problem is observed to only happen on web browsers' pdf viewers (Firefox, Chrome, Edge). On some standalone pdf viewers problem is not present. Also, if `katex` is used the problem doesn't persist.

**Comment by yhatt** [comment]
I think it is bringing from both of line rendering by viewers and thickening by MathJax. (KaTeX is not affected this problem because it will render math typesettings as text with the custom font)

> Yes, there is almost no difference between 1 and 3 when the em-size is 1000. The non-zero amount was to make some very thin areas (like in the italic lower-case "o") less likely to disappear, but I would guess 1 would do just as well. The idea was to have at least some stroke-width, and not just fill, since some areas get very thin.
>
> _— https://github.com/mathjax/MathJax/issues/2618#issuecomment-768543119_

[You can tweak its style for PDF output by `<style>` tag.](https://marpit.marp.app/theme-css?id=tweak-style-through-markdown)

```html
<style>
@media print {
  mjx-container[jax="SVG"] :is(use[data-c], path[data-c]) {
    stroke-width: 0;
  }
}
</style>
```

If this tweak was working well, we may consider to add this style into [Marp Core](https://github.com/marp-team/marp-core) as the default style for MathJax.

**Comment by Prki42** [comment]
Thanks for your reply! This solved the problem. Also, for this to work the newer version of chromium is needed (initially I tried on 88 and it didn't work but when I updated to 99 it worked).
