### ISSUE TITLE
CSS for highlight.js are not picked up since v3.1.1

### ISSUE THREAD

**Issue by mil-ad** [marp-team/marp-core#304]
### Version of Marp Tool

3.2

### Operating System

Linux

### Environment

- OS version: Linux 5.15
- Node.js version (Marpit / Marp Core/ Marp CLI): v18.2.0
- VS Code version (Marp for VS Code): 1.67.2

### How to reproduce

I just noticed my custom CSS for highlight.js (copied from [here](https://github.com/highlightjs/base16-highlightjs/blob/main/themes/gruvbox-light-hard.css)) have stopped working since v.3.1.1

This is probably due to highlight.js dependency getting upgraded to latest versions? I did a bit of searching and didn't come across any breaking changes in recent versions of highlightjs so is it possible there's a problem on Marp's side?

### Expected behavior

![image](https://user-images.githubusercontent.com/686449/171432579-c5f59d1a-b2c5-4197-9104-b59778d24902.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/686449/171432695-aa07b7e4-5ae1-49a8-85cf-46f537a9068b.png)

**Comment by yhatt** [comment]
> This is probably due to highlight.js dependency getting upgraded to latest versions?

Yes. Marp Core v3.x has included major update of highlight.js v10 -> v11. The `base16` themes have actually moved to new locations so you should follow up the latest change at new location.
https://github.com/highlightjs/highlight.js/tree/main/src/styles/base16

> - All [Base16 themes](https://github.com/highlightjs/base16-highlightjs) now live in the `styles/base16` directory - this means some CSS files have moved. Please confirm themes you use reference the new locations.
>
> _&mdash; https://github.com/highlightjs/highlight.js/blob/main/VERSION_11_UPGRADE.md#styles-and-css_

**Comment by mil-ad** [comment]
Thanks those were super helpful pointers. I grabbed the latest style files but still see the same issue. However, I noticed if I add `!important` to everything in the style file things begin to work fine.  🤔

**Comment by yhatt** [comment]
https://github.com/marp-team/marp-core/blob/abc4e2edfae297ba16525270205dcdba161d38f9/themes/default.scss#L62-L76
In the current default theme, most selectors for highlight.js have become the narrowed shape `pre .hljs-xxxxxx` after compiled to CSS, to avoid collision with user-defined class in Markdown. These have `0-1-1` [CSS specificity](https://developer.mozilla.org/docs/Web/CSS/Specificity).

Selectors for highlight also may be required `0-1-1` and higher specificity for overloading. `pre .hljs-xxxx` instead of `.hljs-xxxx`.

**Comment by mil-ad** [comment]
You're absolutely right. That fixed it.

You sir are on top of your stuff. 💪🏼

**Comment by yhatt** [comment]
Update in [v3.2.1](https://github.com/marp-team/marp-core/releases/tag/v3.2.1): Allowed overloading default styles by a simple class definition `.hljs-xxxx` again.  The `pre` element scoping is no longer required as same as v2.x.

Thank you for your feedback!
