### ISSUE TITLE
Content overlap with header and footer in included themes 

### ISSUE THREAD

**Issue by Doctor-love** [marp-team/marp-core#308]
### Version of Marp Tool

Marp CLI v2.0.4

### Operating System

Linux

### Environment

- OS version: Ubuntu 22.04
- Marp CLI v2.0.4 bundle (https://github.com/marp-team/marp-cli/releases/download/v2.0.4/marp-cli-v2.0.4-linux.tar.gz)

### How to reproduce

1. Add a header and/or footer to a presentation with one of the three included themes
2. Fill the slide with content
3. Render slide using Marp CLI

### Expected behavior

Reserved space/margin for header and footer to fit content

### Actual behavior

Slide content overlap with header and footer.  
  
Example 1:
![header_footer_overlap-1](https://user-images.githubusercontent.com/2008673/177164306-fe11b4b5-0a59-4ec6-ab12-26e20b9c4e1c.png)

Example 2:
![header_footer_overlap-2](https://user-images.githubusercontent.com/2008673/177164384-03aa1c93-390e-43af-a3a2-0e2efd9c9b8e.png)
 

### Additional information

The behavior has been observed in the exported PDFs (Chromium) and using Firefox.
To reproduce, create and render a presentation using the following content presentation:
[overlap_demo.md](https://github.com/marp-team/marp-core/files/9039776/overlap_demo.md)

**Comment by yhatt** [comment]
It's a known limitation from CSS absolute positioning for header and footer (`position: absolute`). Content-aware scaling is difficult in HTML rich contents (#197), and the slide author should reduce contents or change the style such as `font-size` for the current slide.

Escape-hatch: In Marp Core v3, you can use `<marp-auto-scaling>` custom element directly for down-scaling. Please enable HTML rendering in the Marp tool you are using.

```markdown
---
header: test
footer: tesxt
style: |
  marp-auto-scaling[data-inside-container] > * {
    min-width: 1280px;
  }
  marp-auto-scaling[data-inside-container]::part(svg) {
    height: 600px;
  }
---

<marp-auto-scaling data-inside-container data-downscale-only>

# Hello

Write your contents here

</marp-auto-scaling>

---

...
```

**Comment by harsh183** [comment]
Awesome! Having more code lines is such a big help
