### ISSUE TITLE
Trouble rendering HTML and Markdown in the same line

### ISSUE THREAD

**Issue by sorousherafat** [marp-team/marp-core#341]
### Version of Marp Tool

Marp VS Code v2.6.0

### Operating System

Linux

### Environment

- OS version: Ubuntu 22.04
- Node.js version (Marpit / Marp Core/ Marp CLI): Node.js 18.0.0
- VS Code version (Marp for VS Code): VS Code 1.78.0

### How to reproduce

write down the following markdown and HTML:

```html
<div>
**Hello**
</div>

<div>

**Hello**

</div>
```

### Expected behavior

both of the `div`s should be rendered **bold**.

### Actual behavior

only the second `div` is rendered **bold**.

![image](https://github.com/marp-team/marp-core/assets/71870584/86d5cdfa-5136-4c29-bdd9-0069d2613a58)

### Additional information

I am willing to contribute to the project and perhaps fix the bug, but I will need some guidance regarding the source code.

**Comment by yhatt** [comment]
This is the result of following [the CommonMark specification](https://spec.commonmark.org/0.30/#example-188). It is not really a bug. The first `<div>` block, without blank lines around contents, should not parse as Markdown text.

> Second, it provides a very simple and flexible way of including Markdown content inside HTML tags: simply separate the Markdown from the HTML using blank lines:
>
> Compare:
>
> ![](https://github.com/marp-team/marp-core/assets/3993388/efd0e671-7566-469d-8976-72e02f824d71)
>
> _&mdash; https://spec.commonmark.org/0.30/#example-188_

See also https://github.com/orgs/marp-team/discussions/192#discussioncomment-3375932.
