### ISSUE TITLE
A Marp constructor option, emoji.twemoji.base, seems not working

### ISSUE THREAD

**Issue by tais9** [marp-team/marp-core#343]
### Version of Marp Tool

Marp cli 2.5.0

### Operating System

Windows

### Environment

- OS version:  Windows 11 and macOS Big Sur 11.4 
- Node.js version Marp CLI 2.5.0
- VS Code version (Marp for VS Code): N/A

### How to reproduce

It seems like twemoji.base is not working. Other options like shortcode and unicode work well.  
For instance, consider the following config file,

options:
  emoji:
    shortcode: ‘twemoji’
    unicode: false
    twemoji:
      base: ‘/twemoji/assets/‘

The generated html file still has jsDeliver link instead of the specified base option.

### Expected behavior

The generated slide deck should have twemojis with the specified base. 

### Actual behavior

Marp’s recently changed default base (jsDeliver) is used.

**Comment by yhatt** [comment]
Good catch. A following test is obviously wrong 😭 

https://github.com/marp-team/marp-core/blob/da3cfbd75cebb84f85b86c79bc541327b2b3aa22/test/marp.ts#L176-L182
