### ISSUE TITLE
TypeError: u2 is not a function

### ISSUE THREAD

**Issue by moguixiaolin** [marp-team/marp-core#361]
![image](https://github.com/marp-team/marp-core/assets/95116912/cbd8a50a-e870-43df-b857-b38f6655f67b)
![image](https://github.com/marp-team/marp-core/assets/95116912/ab00c951-cc68-4885-9908-ee9a88510118)

**Comment by yhatt** [comment]
Need more informations to resolve the issue, such as the version of Marp Core, the runtime operating environment, and whether or not a JavaScript bundler is used. Would you share [the minimum reproducible](https://en.wikipedia.org/wiki/Minimal_reproducible_example) if possible?

**Comment by moguixiaolin** [comment]
操作如下：
`import Marp from '@marp-team/marp-core'`
`const marp = new Marp()`

版本：
![image](https://github.com/marp-team/marp-core/assets/95116912/3edabeac-2878-427a-a219-9e72e4948d97)

页面直接报错如下：
![image](https://github.com/marp-team/marp-core/assets/95116912/a1691e7b-27c7-440f-8744-cb0a9272ff4f)

注意：只进行new 操作，无其他任何操作

**Comment by moguixiaolin** [comment]
> 需要更多信息来解决问题，例如 Marp Core 的版本、运行时操作环境以及是否使用 JavaScript 捆绑器。如果可能的话，你会分享[最低限度的可重复性](https://en.wikipedia.org/wiki/Minimal_reproducible_example)吗？
请看上面

**Comment by yhatt** [comment]
Are you trying to use Marp Core on the Web page? Marp Core library is compatible with JavaScript server environment such as Node.js.

So for getting to work the Marp on the web, you need to set up the JavaScript bundler properly. e.g. Native module polyfills for the browser environment.

For example, both of Marpit and Marp Core depend on PostCSS. https://github.com/postcss/postcss/issues/830 has mentioned that you need to pack JS with using proper browser polyfills to make PostCSS run in the browser.

**Comment by moguixiaolin** [comment]
@yhatt vite 4.x 版本打包通过fallback设置也无法消除 bug 产生。

**Comment by moguixiaolin** [comment]
我的框架： vue + vite +ts
在浏览器运行中出现以上TS的typeerror问题

**Comment by yhatt** [comment]
If you're using Vite, you can inject Node.js polyfills through [vite-plugin-node-polyfills](https://github.com/davidmyersdev/vite-plugin-node-polyfills).

**Comment by moguixiaolin** [comment]
ok，注入后，暂时没有看到其他错误，十分感谢解决方案

**Comment by moguixiaolin** [comment]
ok，注入后，暂时没有看到其他错误，十分感谢解决方案 @yhatt
