### ISSUE TITLE
Nanoid error

### ISSUE THREAD

**Issue by SamonTaikan** [marp-team/marp-core#363]
![image](https://github.com/marp-team/marp-core/assets/145056895/6a481fd4-ef64-4b66-89b6-b3205484518c)
When I used this, I had issue like above Image.
![image](https://github.com/marp-team/marp-core/assets/145056895/c98e2aac-fdad-4c04-9b7d-aa0873757cb6)
Please help about this problem.
If so, what module can I use for Marp format?

**Comment by yhatt** [comment]
Would you share [the minimum reproducible](https://en.wikipedia.org/wiki/Minimal_reproducible_example) if possible?

**Comment by SamonTaikan** [comment]
So can you send me sample code so that I can refer ?

**Comment by yhatt** [comment]
No, I’m requesting to submit a bunch of code that can reproduce the mentioned nanoid error.

ref. [Why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by yhatt** [comment]
We are temporarily closing this issue until additional information necessary for verification and reproduction is provided. If the problem persists, please reopen this issue with the required information.
