### ISSUE TITLE
Images gallery

### ISSUE THREAD

**Issue by piranna** [marp-team/marp-core#364]
Allow to have multiple images one side to other, like a row of commercial labels or sponsors, similar to the `left` and `right` flags, or ideally allow to have absolute (relative?) position of images in a slide.

**Comment by yhatt** [comment]
That is already available by using CSS styles.  For example, to place image(s) in specific absolute position:

```markdown
![](https://example.com/image.jpg)

<style scoped>
img {
  position: absolute;
  left: 50px;
  top: 50px;
}
</style>
```

You also can specify the target image from multiple images, by using [`img:nth-of-type(x)`](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type) selector.

The suitable layout would be different by the slide purpose, so Marp does not provide the layout for specific situations. Add the custom style as you like.
