### ISSUE TITLE
per-element animations

### ISSUE THREAD

**Issue by piranna** [marp-team/marp-core#365]
In addition to slide transitions, add support have per-elements animations like [SliDev](https://sli.dev/guide/animations.html) does. Current support for lists is similar what it does with `<v-clicks>` tag, but there are other more flexible options too to animate independent elements in any order.

**Comment by yhatt** [comment]
Note that _Marp Core has no concept of page switching_. It's up to the downstream tools and libraries whether to take care animations when switching pages. That is a reason why the slide transition is a unique feature by one of templates provided by Marp CLI.

Currently we do not want to force more specific implementations and technologies about Marp's animation to downstream users and developers. Much animation features will bring more complex implementation. Thus, we are keeping animation features for Marp as minimum, and we are designed to make choosable whether to follow animation features at the downstream, as like as current [Marpit's fragmented list](https://marpit.marp.app/fragmented-list?id=rendering).

In addition, more animation features will lead to inflict writing more complex Markdown to users, and also a lot of animated things in the presentation will go against the common principles for creating better slides. This is not the goal for Marp.

But if really you want more animation features on the Marp ecosystem, you can try to make your own page navigation system designed for Marp Core, with a lot of animation features that are injected by Marp(it)'s plugin interface :)

**Comment by piranna** [comment]
I can agree with you, having a minimum features set that can be represented with "vanilla" Markdown syntax, and add extra ones as opt-in plugins makes totally sense to me. Do you know of any actual plugin that implements these per-element animations?
