### ISSUE TITLE
Add support for hgroup

### ISSUE THREAD

**Issue by gwen-lg** [marp-team/marp-core#369]
Hello,

would it be possible to add support of element/tag : [hgroup](https://developer.mozilla.org/fr/docs/Web/HTML/Element/hgroup) ?
In my slideshow, I regularly wanted to add content linked to a title, but not in title.
I see than hgroup seems to be done for this.

In markdown/commonmark side, I imagine than an indented text could be include in hgroup, while no-indented text should be processed like regular text.

Example :
```
# Marp slideshow
  [website](https://marp.app)

Marp is a great tool to easly create slideshow.
```

Thank you

**Comment by yhatt** [comment]
[CommonMark](https://spec.commonmark.org/0.31.2/) does not seem to have a syntax for generating the `hgroup` element as you mentioned. Marp is not a library intended for active extension of Markdown and CommonMark, so we have no plans to adopt such syntax.

However, you can extend your own syntax using [compatible (or created) markdown-it plugins](https://www.npmjs.com/search?q=keywords:markdown-it-plugin) or allow HTML tags to achieve the desired output:

```markdown
<hgroup>

# Marp slideshow

[website](https://marp.app)

</hgroup>
```

**Comment by gwen-lg** [comment]
Ok, thank you
