### ISSUE TITLE
Set starting number for `ol` when list is interrupted

### ISSUE THREAD

**Issue by mil-ad** [marp-team/marp-core#377]
Sometimes I want to have (unindented) blocks between list items but continue the numbering:

```
1. foo
2. bar

blah blah

3. continue
```

but the last item is reset to 1.

Common markdown has this in their documentation:

<img width="974" alt="image" src="https://github.com/marp-team/marp-core/assets/686449/ff654415-5ad6-4f70-9320-0889430e4c77">

but I haven't managed to get it working with marp and also `)` is reserved for fragments anyway.

Is there a way to specify `start`?

**Comment by yhatt** [comment]
Could you provide a minimal reproducible example? In the current version of Marp, the example you've provided looks like not to reset the count of the last list item.

![](https://github.com/marp-team/marp-core/assets/3993388/b6054c47-12d4-45ca-88a8-c77dd01d047b)

Rendered HTML:

```html
<ol>
  <li>foo</li>
  <li>bar</li>
</ol>
<p>blah blah</p>
<ol start="3">
  <li>continue</li>
</ol>
```

**Comment by mil-ad** [comment]
you're right. I can see `start=3` in the HTML but the render is off for me:

<img width="1289" alt="image" src="https://github.com/marp-team/marp-core/assets/686449/32d655a4-4224-48a9-86a9-4c04c7383686">

the indentation doesn't look right 🤔

**Comment by mil-ad** [comment]
oh it's something in my theme/css! Investigating ....

**Comment by mil-ad** [comment]
sorry for the false alarm

**Comment by mil-ad** [comment]
It happened because I wanted to customise the color of the `li` in my css and I ended up doing this:

```
ol {
  li {
    display: block;
  }
  counter-reset: item;
  > li::before {
    font-weight: bold;
    content: counter(item) ". ";
    counter-increment: item;
    color: $enumerate-color;
    position: absolute;
    left: -1.3em;
  }
}
```

And above doesn't seem to pick up the right value when we have `start`

**Comment by yhatt** [comment]
If you had defined the custom counter `item` for the list in your CSS, you also have to manage resetting the counter by `<ol start="x">`. So that means you should make inefficient definitions like following:

```css
ol[start="1"] {
  counter-reset: item 0;
}
ol[start="2"] {
  counter-reset: item 1;
}
ol[start="3"] {
  counter-reset: item 2;
}
/* ...more ol[start="x"] definitions... */
```

Reference: https://stackoverflow.com/questions/23699128/how-can-i-reset-a-css-counter-to-the-start-attribute-of-the-given-list

**Another solution**: You also can use the implicitly defined counter `list-item` by `<ol>` and `<li>` instead of defining the custom counter.
https://www.w3.org/TR/css-lists-3/#list-item-counter

```markdown
<style>
li {
  display: list-item;
  list-style: none;
}

li::before {
  content: counter(list-item) ". ";
  font-weight: bold;
  background: red;
  color: white;
}
</style>

1. foo
2. bar

blah blah

3. continue
```

![untitled](https://github.com/marp-team/marp-core/assets/3993388/6afa3a11-2721-4bdb-8f34-4a7e718ff09a)

> [!NOTE]
> Due to the bug of Chromium (Chrome), the live preview provided by Marp for VS Code or other Marp tools may not apply the updation of the starting number immidiately. 
> https://issues.chromium.org/issues/40253067

**Comment by mil-ad** [comment]
Thanks for that @yhatt!

I changed mine to below and it seems to be working:

```
ol {
  li::marker {
    color: red;
    font-weight: bold;
  }
}
```
