### ISSUE TITLE
PDF not being rendered with background image

### ISSUE THREAD

**Issue by spkane** [marp-team/marp-core#54]
I am using `marp-cli` via the Docker container and although it is working in general, the PDF files are not being rendered with the background image in my custom theme, although it works fine in the HTML. 

Should this work and do you have any ideas or pointers on how I could troubleshoot this?

Here are some details about the setup and workflow...

On a Mac OS X system in a directory with the following files:

```
class-docker-compose.md
images/chalkboard-16by9.jpg
sunburst.css
spkane.css
```

I am running the following commands:

```
docker pull marpteam/marp-cli
docker run --rm -v $PWD:/home/marp/app/ marpteam/marp-cli class-*.md --theme-set spkane.css
docker run --rm -v $PWD:/home/marp/app/ marpteam/marp-cli class-*.md --theme-set spkane.css --pdf
```

**Comment by yhatt** [comment]
@spkane Please try `--allow-local-files` option. PDF conversion in Marp CLI cannot use local file resources by default because of the security reason.

```
docker run --rm -v $PWD:/home/marp/app/ marpteam/marp-cli class-*.md --theme-set spkane.css --pdf --allow-local-files
```

Working to write the documentation that included this tip is [now in progress](https://github.com/marp-team/marp-cli/tree/docs#convert-to-pdf).

**Comment by spkane** [comment]
That did the trick. Thank you very much. I pretty sure that the directions and option in help weren't there when I started working on this, but I am really glad to see the progress.

I know that this is still heavily in development, but it has been very helpful! Thank you for all the hard work!!
