### ISSUE TITLE
Test on top of page

### ISSUE THREAD

**Issue by jerCarre** [marp-team/marp-core#78]
When I use the default theme, the text appeared in the middle of the page. 
How can I force the text on top with a css which import the default ?

**Comment by yhatt** [comment]
Transfered issue from Marpit ▶️ Marp Core :truck:

Try this:

```markdown
<style>section { justify-content: start; }</style>

# Text on top

foobar
```

![text on top](https://user-images.githubusercontent.com/3993388/54617656-04acbf00-4aa5-11e9-992b-560fecda7f25.png)

**Comment by jerCarre** [comment]
Perfect !!

Thx

**Comment by mcamurri** [comment]
I'm sorry but  it seems not to work for me. Here's what I've got:
```
---
marp: true
---

<style>section { justify-content: start; }</style>

# Text on top

foobar
```
and it produces this:

![Image](https://github.com/user-attachments/assets/f816c6a5-407c-46e0-8a2d-1ea44e0b2180)

I'm using Marp for VS code version `3.1.1` on Ubuntu 20.04 and VS Code 1.98.2

HTML is active on VS Code and other `<style>` tags work (e.g. chaging the background color):

![Image](https://github.com/user-attachments/assets/c301b92f-c13d-4efb-a388-849d53ee4234)

**Comment by yhatt** [comment]
@mcamurri Refer to https://github.com/marp-team/marp-vscode/issues/480#issuecomment-2568944021. The latest Marp Core v4 (that is using by the latest Marp for VS Code v3) is no longer used Flexbox so `justify-content: start;` will not work. Use `align-content: start;` instead.
