### ISSUE TITLE
Math not rendering

### ISSUE THREAD

**Issue by elbaro** [marp-team/marp-core#83]
```
$L = \sum_i w(x) L(f(X_i), Y_i)$  // render
$L = \sum_i w(x) L(f(X_i), Y_i) $ // does not render
$ L = \sum_i w(x) L(f(X_i), Y_i)$ // does not render
```

**Comment by yhatt** [comment]
Transferred from marp-vscode ▶️ marp-core 🚚

It just a correct behavior. We are following a syntax of [Pandoc](http://pandoc.org/MANUAL.html#math)

> The opening `$` must have a non-space character immediately to its right, while the closing `$` must have a non-space character immediately to its left, and must not be followed immediately by a digit.
